# Clone of https://github.com/clowrey/esphome-geekmagic-small-TV-pro/blob/main/geekmagic-lvgl-working-ESP32E-N8R2
# adapted for "Geekmagic-S3" "DIY" variant sold at https://www.aliexpress.us/item/3256807368227919.html
# Pin mappings from https://github.com/GeekMagicClock/GeekMagic-S3:
#  - SPI and TFT pin mappings in
#    https://github.com/GeekMagicClock/GeekMagic-S3/blame/80b631c8c10dd79f2e198e56fbdfb7fa85e51681/lib/TFT_eSPI/User_Setup.h#L223-L229C39
#  - Touch button pin mapping in
#    https://github.com/GeekMagicClock/GeekMagic-S3/commit/9901fb56abb27c46f693ca511e1788bfbc915a4a#diff-6b5336478a255e79fdeb0c3c678393b7f49e21bdd4ac419cc      bc9633d0587bbadR7
# For GeekMagic-S3 display
substitutions:
  device_name: geekmagic-s3-display
  SPI_SCLK_PIN: GPIO12
  SPI_MOSI_PIN: GPIO11
  TFT_DC_PIN: GPIO7
  TFT_RESET_PIN: GPIO6
  TFT_BACKLIGHT_PIN: GPIO14
  TOUCH_BUTTON_PIN: GPIO9 # a.k.a. TOUCH9 on ESP32-S3
  # shorter sampling time for S3 per https://community.home-assistant.io/t/esp32-s3-touch-sensor/667563/2
  TOUCH_BUTTON_MEASUREMENT_DURATION: 0.25ms
  TOUCH_BUTTON_THRESHOLD: "130000"

# For GeekMagic-Pro display
#substitutions:
#  device_name: geekmagic-pro-display
#  SPI_SCLK_PIN: GPIO18
#  SPI_MOSI_PIN: GPIO23
#  TFT_DC_PIN: GPIO2
#  TFT_RESET_PIN: GPIO4
#  TFT_BACKLIGHT_PIN: GPIO25
#  TOUCH_BUTTON_PIN: GPIO32
#  TOUCH_BUTTON_MESUREMENT_PERIOD: 4ms
#  TOUCH_BUTTON_THRESHOLD: 1375

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  # esp32-s3-devkitc-1 board specifies no PSRAM, so override here
  # per https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto/652601
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_ap_password

captive_portal:

debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# Define a PWM output on the ESP32
output:
  - platform: ledc
    pin: ${TFT_BACKLIGHT_PIN}
    inverted: True
    id: backlight_pwm

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

esp32_touch:
  setup_mode: false
  measurement_duration: ${TOUCH_BUTTON_MEASUREMENT_DURATION}

binary_sensor:
  - platform: esp32_touch
    name: "Touch Button ${device_name}"
    pin: ${TOUCH_BUTTON_PIN}
    threshold: ${TOUCH_BUTTON_THRESHOLD}
    #internal: true
    on_click:
      then:
        lvgl.page.next:

spi:
  clk_pin: ${SPI_SCLK_PIN}
  mosi_pin: ${SPI_MOSI_PIN}
  interface: hardware
  id: spihwd

display:
  - platform: ili9xxx
    id: lcd_display
    model: st7789v
    spi_id: spihwd
    #data_rate: 20MHz #oringal device uses 20mhz - 40 is default and works - does not work at 80mhz
    #cs_pin: GPIO03 #CS pin is connected to gnd I believe
    dc_pin: ${TFT_DC_PIN}
    reset_pin: ${TFT_RESET_PIN}
    spi_mode: MODE3   #since no cs pin default is mode0
    dimensions:
      width: 240
      height: 240
      offset_height: 0
      offset_width: 0
    invert_colors: true
    update_interval: never
    auto_clear_enabled: false

time:
  - platform: sntp
    id: time_comp

number:
  - platform: template
    initial_value: 0
    id: counting_number
    internal: True
    min_value: -10
    max_value: 10
    step: 1
    optimistic: True

sensor:
  - platform: wifi_signal
    # name: "WiFi Signal Sensor"
    internal: True
    id: wifi_signal_sensor
    update_interval: 1s
  - platform: uptime
    id: uptime_counter
    update_interval: 1s
    accuracy_decimals: 0
    on_raw_value:
      then:
        - number.increment:
            id: counting_number
            cycle: True
        - script.execute: update_display
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"
  - platform: homeassistant
    id: ha_battery_power_net
    entity_id: sensor.emporia_garage_total_power
    #internal: True
    on_value_range:
      - above: 0.0
        then:
          - lvgl.label.update:
              id: battery_charging_discharging
              text_color: 0x00FF00
              text: "charging"
          - lvgl.label.update:
              id: label_battery_power
              text_color: 0x00FF00
      - below: 0.0
        then:
          - lvgl.label.update:
              id: battery_charging_discharging
              text_color: 0xFF0000
              text: "discharging"
          - lvgl.label.update:
              id: label_battery_power
              text_color: 0xFF0000

script:
  - id: update_display
    then:
      - lvgl.indicator.update:
          id: indicator_battery_power
          value: !lambda return id(counting_number).state * 10; #multiply by 10 because LVGL meter only supports integers
      - lvgl.label.update:
          id: label_battery_power
          text:
            format: "%.1fkW"
            args: [ 'id(ha_battery_power_net).state' ]
      - lvgl.label.update:
          id: label_battery_soc
          text:
            format: "%.1f%%"
            args: [ 'id(counting_number).state' ]
      - lvgl.label.update:
          id: label_house_power
          text:
            format: "%.1fkW"
            args: [ 'id(ha_battery_power_net).state' ]
      - lvgl.label.update:
          id: label_hydro_power
          text:
            format: "%.1fkW"
            args: [ 'id(counting_number).state' ]
      - lvgl.label.update:
          id: label_solar_power
          text:
            format: "%.1fkW"
            args: [ 'id(ha_battery_power_net).state' ]
      - lvgl.label.update:
          id: label_dump_load
          text:
            format: "%.1fkW"
            args: [ 'id(ha_battery_power_net).state' ]


      #- lvgl.img.update:
          #id: img_power
          #src: power_icon
          #img_recolor: 0xFFF000 #mixes this color with the base image
          #img_recolor_opa: 100% #opacity defaults to 0% = must set this for recolor to take effect
          #bg_color: 0xFFFFFF

image:
  - file: mdi:car-battery
    id: icon_battery
    resize: 35x35
    type: BINARY
  - file: mdi:home-lightning-bolt-outline
    id: icon_house
    resize: 35x35
    type: BINARY
  - file: mdi:hydro-power
    id: icon_hydro
    resize: 35x35
    type: BINARY
  - file: mdi:sun-wireless-outline
    id: icon_solar
    resize: 35x35
    type: BINARY
  - file: mdi:resistor
    id: icon_dump_load
    resize: 35x35
    type: BINARY
  - file: mdi:navigation
    id: icon_pointer
    resize: 40x20
    type: BINARY
    # mdi:sun-wireless-outline
    # mdi:solar-power
    # mdi:battery-charging-outline
    # mdi:battery-arrow-up-outline
    # mdi:battery-arrow-down-outline
    # mdi:lightning-bolt

lvgl:
    log_level: INFO
    color_depth: 16
    bg_color: 0
    border_width: 0
    outline_width: 0
    #shadow_width: 0
    text_font: unscii_16
    align: center
    style_definitions:
      - id: font_style
        text_font: MONTSERRAT_28
        #text_font: unscii_16
        align: center
        text_color: 0xFFFFFF
        #bg_opa: cover
        bg_opa: TRANSP
        bg_color: 0
        radius: 4
        pad_all: 2
      - id: details_style
        text_font: MONTSERRAT_16
        align: center
        text_color: 0xFFFFFF
        #bg_opa: cover
        bg_opa: TRANSP
        bg_color: 0
        radius: 4
        pad_all: 2
    page_wrap: true
    pages:
      - id: main_page
        widgets:
          - obj: # Meter
              height: 240 # needed to be explicitily defined for my round display to not have weird border line overlapping gauge
              width: 240
              align: center
              bg_color: 0
              #bg_opa: TRANSP
              border_width: 0
              outline_width: 0
              #shadow_width: 0
              pad_all: 0
              scrollbar_mode: "off"
              clip_corner: true
              radius: 120
              widgets:
                - meter: # Gradient color  arc
                    height: 100%
                    width: 100%
                    border_width: 0
                    outline_width: 0
                    align: center
                    bg_color: 0
                    #bg_opa: TRANSP
                    scales:
                      angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                      range_from: -100
                      range_to: 100
                      ticks:
                        count: 0
                      indicators:
                        - line:
                            id: indicator_battery_power
                            width: 8
                            color: 0xFFFFFF
                            r_mod: 20 #increase radius to maximize screen utilization
                            value: 0 # initial value
                        #- img:
                        #    src: icon_house #doesnt seem to be fully implemented yet
                        #    id: indicator_battery_power
                        #    value: 0 # initial value
                        - arc:
                            color: 0xFF3000
                            r_mod: 20 #increase radius to maximize screen utilization
                            width: 26
                            start_value: -100
                            end_value: 0
                        - arc:
                            color: 0x00FF00
                            r_mod: 20
                            width: 26
                            start_value: 0
                            end_value: 100
                - obj: # to erase middle part of meter indicator line
                    height: 180
                    width: 180
                    radius: 90 #should be half of the height, width to make a circle
                    align: center
                    border_width: 0
                    pad_all: 0
                    bg_color: 0
                - label: # gauge lower and higher range indicators
                    styles: font_style
                    text_font: MONTSERRAT_18 # override font size
                    y: 10 #positive = lower
                    x: -102
                    text: "-10"
                - label:
                    styles: font_style
                    text_font: MONTSERRAT_18 # override font size
                    y: 10
                    x: 102
                    text: "+10"
                - label:
                    styles: font_style
                    id: label_battery_power
                    y: -70 #negative = higher
                - label:
                    styles: font_style
                    id: battery_charging_discharging
                    hidden: true #turn off for now
                    y: -35
                - label:
                    styles: font_style
                    #text_font: MONTSERRAT_32 # override font size
                    id: label_battery_soc
                    y: -38
                    x: 30 #positive = to the right of center
                - label:
                    styles: font_style
                    id: label_house_power
                    text_color: 0xffffff
                    y: -6 #positive = below center
                    x: 30 #positive = to the right of center
                - label:
                    styles: font_style
                    id: label_hydro_power
                    text_color: 0x1e90ff
                    y: 26 #positive = below center
                    x: 30 #positive = to the right of center
                - label:
                    styles: font_style
                    id: label_solar_power
                    text_color: 0xffff00
                    y: 58 #positive = below center
                    x: 30 #positive = to the right of center
                - label:
                    styles: font_style
                    id: label_dump_load
                    text_color: 0xff0000
                    y: 90 #positive = below center
                    x: 30 #positive = to the right of center
                - image:
                    src: icon_battery
                    align: center
                    image_recolor: 0xffffff
                    image_recolor_opa: 100% #opacity defaults to 0% = must set this for recolor to take effect
                    y: -38 #positive = below center
                    x: -40 #negative = to the left
                - image:
                    src: icon_house
                    align: center
                    image_recolor: 0xffffff
                    image_recolor_opa: 100% #opacity defaults to 0% = must set this for recolor to take effect
                    y: -6 #positive = below center
                    x: -40 #negative = to the left
                - image:
                    src: icon_hydro
                    #id: img_hydro
                    align: center
                    image_recolor: 0x1e90ff
                    image_recolor_opa: 100% #opacity defaults to 0% = must set this for recolor to take effect
                    y: 26 #positive = below center
                    x: -40 #negative = to the left
                - image:
                    src: icon_solar
                    #id: img_hydro
                    align: center
                    image_recolor: 0xffff00
                    image_recolor_opa: 100% #opacity defaults to 0% = must set this for recolor to take effect
                    y: 58 #positive = below center
                    x: -40 #negative = to the left
                - image:
                    src: icon_dump_load
                    #id: img_hydro
                    align: center
                    image_recolor: 0xff0000
                    image_recolor_opa: 100% #opacity defaults to 0% = must set this for recolor to take effect
                    y: 90 #positive = below center
                    x: -40 #negative = to the left
      - id: advanced
        widgets:
          - label:
              styles: font_style
              text_font: MONTSERRAT_18 # override font size
              y: 0 #negative = higher
              x: 0
              text: "Settings Page"
